name: app-02
on: push
jobs:
  build-test-package:
    name: Build, test, & containerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
      
      - name: Containerize
        run: docker build -t app-02 .